version: "3"

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - inception
    ports:
      - "80:80"
      - "8080:8080"

networks:
  inception:
    driver: bridge
